function [] = make_ieee_figures()
set(0,'DefaultTextFontName','Times',...
    'DefaultTextFontSize',9,...
    'DefaultAxesFontName','Times',...
    'DefaultAxesFontSize',9,...
    'DefaultLineLineWidth',1,...
    'DefaultLineMarkerSize',2);


end

